### ISSUE TITLE
Please remove usages of branch property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.sdrangel.SDRangel#61]
https://github.com/flathub/org.sdrangel.SDRangel/blob/fd7f302f52211917e498a60f3eeeba41b4ab7f79/org.sdrangel.SDRangel.yaml#L237

should be tag or commit or tag+commit

**Comment by AsciiWolf** [comment]
I would prefer to keep it as it is for now to indicate that the new-namespaces branch should be used for this repo instead of master (because master is broken and outdated). The branch property does not seem to cause any harm.

**Comment by bbhtt** [comment]
We will be blocking it via the linter.

> he new-namespaces branch should be used for this repo instead of master (because master is broken and outdated)

Put a comment above it.

>  The branch property does not seem to cause any harm.

If the head of the branch goes out of sync with the commit used below, the build will silently fail. It does cause issues, which is why we are blocking it.

**Comment by AsciiWolf** [comment]
Ah, makes sense. I will make a PR to change the branch properties into comments. Thanks!
