### ISSUE TITLE
Set ARCH_OPT to nehalem for compatibility with older CPUs

### ISSUE THREAD

**Issue by srcejon** [flathub/org.sdrangel.SDRangel#63]
See: https://github.com/f4exb/sdrangel/issues/2081

**Comment by AsciiWolf** [comment]
Test build will be ready in #65. Feel free to try it and report if it makes the SDRangel Flatpak working on older CPUs. Thanks!

**Comment by AsciiWolf** [comment]
Thanks for the test!

> Hi AsciiWolf, I have tested at 12:51 CEST 25-th APRIL 2024 the latest snap sdrangel build.

Did you mean Flatpak build?
