### ISSUE TITLE
SDRANGEL does not start with Flatpak 1.14.4 on Intel(R) Core(TM) i5-3230M CPU - SSE 4.2 presented in CPU

### ISSUE THREAD

**Issue by Lat6819** [flathub/org.sdrangel.SDRangel#64]
Hi, I have old notebook X230 with Intel(R) Core(TM) i5-3230M CPU. I have checked twice - my CPU has SSE 4.2. I checked on internet and with command lscpu. So my CPU is capable to run SDRANGEL.
I have tried FLATHUB and SNAP. I have tried X11 and WAYLAND. SDRANGEL does not start. 
System: 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux - Debian 12
Flatpak 1.14.4
snap    2.61.2
snapd   2.61.2
series  16
debian  12
kernel  6.1.0-20-amd64

**Comment by AsciiWolf** [comment]
Probably the same problem as mentioned in #63. Closing this ticket.
