### ISSUE TITLE
ADS-B demodulation map no longer zoomable

### ISSUE THREAD

**Issue by CocolinoFan** [flathub/org.sdrangel.SDRangel#84]
Hello, 

I noticed that the ADS-B map no longer allows zooming in and out. I am 90% sure this happened after the last commit [6a82587](https://github.com/flathub/org.sdrangel.SDRangel/commit/6a8258740be67d16105b7138832137cecc9525ab), if not, it was the commit before that for sure.

**Comment by CocolinoFan** [comment]
OK, I did some testing and it is the last commit (6a82587) that introduced the problems:
1) Can no longer zoom in and out in the ADS-B demodulator map
2) ADS-B demodulator is missing the `mapboxgl` Map provider (which is not great as they have this "Street" map that is really good)

**Comment by AsciiWolf** [comment]
Please report it as an [upstream bug](https://github.com/f4exb/sdrangel/issues) related to the Qt6 build. I am not a SDRangel developer, this Flatpak is unofficial and unsupported by the actual developer.

**Comment by CocolinoFan** [comment]
https://github.com/f4exb/sdrangel/issues/2318
